### PR TITLE
modified get-libsnark for successful compiling

### PR DESCRIPTION
**Pull request by arielgabizon**
added NO_PROCPS=1
and switched to ALT_BN128
before that didn't compile
It got stuck while trying to clone 
https://github.com/herumi/xbyak

### CODE REVIEW

**Comment by arielgabizon** [comment]
I also had to add 
`const std::string annotation_prefix;`
in objects in snark/gadget.hpp to get make to work

**Comment by ebfull** [comment]
Neat, thanks.

**Comment by arielgabizon** [comment]
hmm I haven't managed to get the cargo part working yet so not sure how useful it is in itself..

**Comment by 3for** [comment]
Remember to remove the `Cargo.lock` before compiling.
Use the cargo nightly version works.

**Pull request merged**
